spring:
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    serialization:
      indent-output: true
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    open-in-view: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.jdbc.batch_size: 25
      hibernate.jdbc.batch_versioned_data: true
      hibernate.order_inserts: true
      hibernate.order_updates: true
  application:
    name: 'BoilerplateApp'
management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers,prometheus
      base-path: /management
# Application properties
application:
  security:
    authentication:
      jwt:
        base64-secret: ZTc2MjU3YWQyOGFhY2M0NDE4YTZkNDFiMjE5Yjk5YTgxNDQ1NDliYmEwZDBlZWYwODVkNjdhNzVlZDA1ZWRkZTRjZTgxYmViNDljZjI2NmYwY2FlYjNjMWE3MmY2Y2I4OWJlMGVjZTZmZjlkMGEyMjNmZjYzY2UwNGI1ZmNjZjY=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  credentials:
    username: kiabi
    password: kiabi123