# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# ===================================================================
server:
  servlet:
    context-path: {{ BOILERPLATE_CONTEXT_PATH }}
  tomcat:
    ajp-port: {{ BOILERPLATE_AJP_PORT }}
spring:
  application:
    name: BOILERPLATE_APPLICATION_NAME
  profiles:
    active:  #spring.profiles.active#
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    #show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: {{ BOILERPLATE_DB_URL }}
    username: {{ BOILERPLATE_DB_USERNAME }}
    password: {{ BOILERPLATE_DB_PASSWORD }}
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  resources:
    add-mappings: true
  liquibase:
    change-log: classpath:config/liquibase/master.xml
  thymeleaf:
    mode: HTML
    cache: true
  mail:
    host: localhost
    port: 25
    username:
    password:
# Application properties
application:
  security:
    authentication:
      jwt:
        secret: my-secret-token-to-change-in-production
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  mail:
    from: boilerplate@localhost
    base-url: http://127.0.01:8080
  store:
    impl: com.lagab.cmanager.store.impl.FileSystemStore
    root-dir: C:\Users\gladislas\Documents\Fragments
    upload-dir: ${application.store.root-dir}/upload
    tmp-dir: ${application.store.root-dir}/tmp
    # Set the part size (in bytes) for multipart uploads. Defaults to 20 mb.
    maxSize: 20971520
    # A file extension of * will permit all file extensions.
    file-extensions: "*"
    #file-extensions: .ico,.bmp,.css,.doc,.docx,.dot,.gif,.gz,.htm,.html,.jpg,.js,.lar,.odb,.odf,.odg,.odp,.ods,.odt,.pdf,.png,.ppt,.pptx,.rtf,.swf,.sxc,.sxi,.sxw,.tar,.tiff,.tgz,.txt,.vsd,.xls,.xlsx,.xml,.zip,.jrxml
    allowed-mime-types: =text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml,text/csv,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.oasis.opendocument.presentation,application/vnd.oasis.opendocument.spreadsheet,application/vnd.oasis.opendocument.text,application/vnd.ms-powerpoint,application/vnd.openxmlformats-officedocument.presentationml.presentation,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,font/woff,font/woff2,font/ttf,font/otf,application/x-rar-compressed,application/x-tar,application/zip,application/x-7z-compressed,image/vnd.microsoft.icon,image/gif,image/x-icon,image/jpeg,image/png,image/svg+xml # Comma-separated list of MIME types that should be used.
    char-blacklist: \\\\,//,:,*,?,\",<,>,|,../,/..
# Properties to be exposed on the /info management endpoint
#info:
